spring:
  application:
    name: eureka
server:
  port: 10000

eureka:
  client:
#    默认情况下，Eureka Server 也是一个普通的微服务，所以当它还是一个注册中心的时候，他会有两层
#    身份：1.注册中心；2.普通服务，即当前服务会自己把自己注册到自己上面来
    # register-with-eureka 设置为 false，表示当前项目不要注册到注册中心上
    register-with-eureka: false
    # 表示是否从 Eureka Server 上获取注册信息
    fetch-registry: false
