spring:
  application:
    name: resilience4j





server:
  port: 9003



resilience4j:
  retry:
    retry-aspect-order: 399  # 表示Retry的优先级
    backends:
      retryA:
        maxRetryAttempts: 5  #重试的次数
        waitDuration: 500 #重试的等待时间
        exponentialBackoffMultiplier: 1.1 # 间隔乘数
        retryExceptions:
          - java.lang.RuntimeException
  circuitbreaker:
    instances:
      cbA:
        ringBufferSizeInClosedState: 5   # 关闭状态下环形缓冲区的大小
        ringBufferSizeInHalfOpenState: 3 #
        waitInterval: 5000  # 断路器保持打开的时间，在到达设置的时间之后，断路器会进入到 half open 状态
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
    circuit-breaker-aspect-order: 398


eureka:
  client:
    service-url:
      defaultZone:  http://localhost:10000/eureka
